# Generated by Django 3.2.6 on 2022-06-21 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inventory_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_no', models.CharField(max_length=10)),
                ('loc', models.CharField(max_length=10)),
                ('user', models.CharField(max_length=20)),
                ('des', models.TextField()),
                ('brand', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('date_purchase', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'inventories',
            },
        ),
    ]
